app/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#intro'

  get 'home/listener' => 'home#listener'
  get 'home/musician' => 'home#musician'

  post 'performers/lookup' => 'performers#lookup'
  get 'performers/search' => 'performers#search'
  get 'performers/show' => 'performers#show'
  get 'performers' => 'performers#index'

  get 'performers/edit' => 'performers#show'
  get 'performers/new' => 'performers#new'

  get 'performers/delete' => "performers#delete"
  post 'performers' => 'performers#create'

  resources :sessions
  post 'sessions/new', to: 'sessions#create'
  get 'log_out' => 'sessions#destroy', :as => "log_out"

  post '/sms' => 'sms#create'
  get '/sms' => 'sms#create'

end

app/app/models/listener.rb
class Listener < ActiveRecord::Base
end

app/app/models/performer.rb
class Performer < ActiveRecord::Base
  has_secure_password

  validates_uniqueness_of :email

  attr_accessible :name, :email, :password, :password_confirmation

  def position=(p)
    RedisCache.redis.set("#{self.id}.position", p)
  end
  def position()
    return RedisCache.redis.get("#{self.id}.position")
  end
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    private

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def authorize
        redirect_to login_url, alert: "Not authoriezd" if current_user.nil?
    end
end

app/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/app/controllers/listeners_controller.rb
class ListenersController < ApplicationController


end

app/app/controllers/performers_controller.rb
class PerformersController < ApplicationController
    def index
    end

    def create
        # render text: params[:performer].inspect
        @performer = Performer.new(performer_params)
        if @performer.save
            session[:performer_id] = @performer.id
            redirect_to ""
        else
            redirect_to ""
        end
    end

    def new
        @performer = Performer.new
    end

    def show
        if session[:performer_id]
            @performer = Performer.find(session[:performer_id])
        else
            @performer = Performer.find(params[:format])
        end

    end

    def edit
        # an artist can edit his profile
    end

    def destroy
        @performer = Performer.find(params[:id])
        @performer.destroy

        redirect_to ""
    end

    def lookup
        listener_position = params[:position]
        @performers = Performer.all

        render :json => Performer.all.map { |p| { 'id' => p.id, 'name' => p.name, 'position' => p.position } }
        # you need to POST to /lookup with param 'position', this param will be the value of navigator.geolocation.getCurrentPosition
    end

    def search
        listener_position = params[:position]
        @performers = Performer.all
        # you need to POST to /lookup with param 'position', this param will be the value of navigator.geolocation.getCurrentPosition
    end

    private
        def performer_params
            params.require(:performer).permit(:name, :email, :password, :password_confirmation)
        end
end

app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        performer = Performer.find_by_email(params[:session][:email])
        if performer && performer.authenticate(params[:session][:password])
            session[:performer_id] = performer.id
            redirect_to "", notice: "logged in"
        else
            flash.now.alert = "Email or password is invalid"
            redirect_to "/sessions/new"
        end
    end

    def destroy
        session[:performer_id] = nil
        redirect_to root_url, notice: "Logged out!"
    end
end

app/app/controllers/sms_controller.rb
# require 'twilio-ruby'

# class SmsController < ApplicationController
#   skip_before_filter :force_ssl # You may need this if your app uses https normally
#   skip_before_filter :verify_authenticity_token

#   def create

#     # render text: "test"
#     # Do something with params['From'] -- contains the phone number the SMS came from
#     # Do something with params['Body'] -- contains the text sent in the SMS

#     # <Reponse/> is the minimum to indicate a "no response" from Twilio
#     render xml: "
#         <Response>
#             <Message>Hey Monkey. Thanks for the message!</Message>
#         </Response>"
#     end
# #   TWILIO_SID = 'AC2a3e7b30d28bae4ca313834c1c07bd63'
# #   TWILIO_AUTH_TOKEN = 'de74b27c8306aab8f8544e652d2fb515'

#   # def create
#   #   client = Twilio::REST::Client.new(TWILIO_SID, TWILIO_AUTH_TOKEN)
#   #   client.account.messages.create(
#   #     :from => '+14432192344',
#   #     :to => '+14438516506',
#   #     :body => 'Hey there!'
#   #   )
#   # end
# end


class SmsController < ApplicationController
  skip_before_filter :force_ssl # You may need this if your app uses https normally
  TWILIO_SID = 'AC2a3e7b30d28bae4ca313834c1c07bd63'
  TWILIO_AUTH_TOKEN = 'de74b27c8306aab8f8544e652d2fb515'

  def create
    client = Twilio::REST::Client.new(TWILIO_SID, TWILIO_AUTH_TOKEN)
    client.account.messages.create(
      :from => '+14432192344',
      :to => '+14438516506',
      :body => 'Hey there!'
    )
    render text: "asdf"
  end
end

app/app/controllers/twilio_controller.rb
require 'rubygems'
require 'twilio-ruby'

class TwilioController < ApplicationController
    def receive
        message_body = params["Body"]
        from_number = params["From"]

        response = Twilio::TwiML::Response.new do |r|
          r.Message "help this doesnt work"
        end

        # SMSLogger.log_text_message from_number, message_body

        render_twiml response
    end





    def send
        number_to_send_to = params[:number_to_send_to]

        twilio_sid = "PNd0c2e6ab4dd1dc560f4fddec5067ca23"
        twilio_token = "9fe16dc5d670197e1bd8b4d368a0407e"
        twilio_phone_number = "6467366536"

        @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token

        @twilio_client.account.sms.messages.create(
          :from => "+1#{twilio_phone_number}",
          :to => number_to_send_to,
          :body => "This is an message. It gets sent to #{number_to_send_to}"
        )
    end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/home_helper.rb
module HomeHelper
end

app/app/helpers/listeners_helper.rb
module ListenersHelper
end

app/app/helpers/performers_helper.rb
module PerformersHelper
end

app/app/helpers/sessions_helper.rb
module SessionsHelper
end

app/app/helpers/sms_helper.rb
module SmsHelper
end

app/app/helpers/twilio_helper.rb
module TwilioHelper
end

app/app/views/home/intro.html.erb
<!DOCTYPE html>
<html>
  <head>

  </head>
  <body>
    <div id="bg">
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:700' rel='stylesheet' type='text/css'>
    </div>
    <h1>Street Music</h1>
    <% if session[:performer_id] %>
    <h2 id="welcome">Welcome, <%= Performer.find(session[:performer_id])[:email] %>!</h2>
    <% end %>
    <input type="submit" value="Listener" onclick="window.location='/home/listener';"/>
    <br/><br/>
    <input type="submit" value="Musician" onclick="window.location='/home/musician';"/>
    <br/><br/>
    <input type="submit" value="Logout" onclick="window.location='log_out';"/>
    <br/>



  </body>
</html>

app/app/views/home/listener.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <div id="bg">
    <h1>Listener Menu</h1>

<!--         <input type="submit" value="Maps" onclick="window.location='/performers';"/>
    <br/> -->
        <input method="post" type="submit" value="Lookup" onclick="window.location='/performers/search';"/>
    <br/> </br>
        <input type="submit" value="View" onclick="window.location='/performers';"/>


  </body>
</html>

app/app/views/home/musician.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <div id="bg">
    <h1>Musician Menu</h1>
<!--     <form action="post.html" method="get">
        <input type="submit" value="Post" name="post" id="post"/>
    </form> -->
    <% if session[:performer_id] %>
    <h2 id="welcome">Welcome, <%= Performer.find(session[:performer_id])[:email] %>!</h2>
    <br/>
    <form action="/performers/edit" method="get">
        <input type="submit" value="Profile" onclick="window.location='/performers/edit';"/>
    </form>

    <% end %>


<br/>
    <form action="/sessions/new" method="get">
        <input type="submit" value="Log In" onclick="window.location='/sessions/new';"/>
    </form>
<br/>
    <form action="/performers/new" method="get">
        <input type="submit" value="Register" onclick="window.location='/performers/new';"/>
    </form>

  </body>
</html>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/app/views/performers/index.html.erb
<!-- finding performers! -->


<script>
  $(document).ready ( lookupPerformers );

</script>


<!-- <br />
<a href="lookup">are you a performer? signup now</a> -->


<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map-canvas { height: 100%; width: 70%; float: right;}
      #left {float: left; height: 100%; width: 30%;}
    </style>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBsZcIOcxv6LMjgknDGOev1tSu-G3x4v5E"></script>
    <script type="text/javascript" src=""></script>
    <%= javascript_include_tag :maps %>



    <script>



    var map;
    var marker;
    window.lat = 42.3581;
    window.lon = -71.0636;

    navigator.geolocation.getCurrentPosition(
      function(p) {
        window.lat = p.coords.latitude;
        window.lon = p.coords.longitude;
        // console.log(lat,lon);
      },
      function(e) {
      }
    );

    function initialize() {
      var mapOptions = {
        center: new google.maps.LatLng(window.lat, window.lon),
        zoom: 14
      };
      window.map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
      var myLatlng = new google.maps.LatLng(window.lat, window.lon);
      var mapOptions = {
        zoom: 4,
        center: myLatlng
      }

      // To add the marker to the map, use the 'map' property
      marker = new google.maps.Marker({
          position: myLatlng,
          map: map,
          title:"Your position",
          icon: "/user.png"
      });
    }
    google.maps.event.addDomListener (window, 'load', initialize);

    function moveMarker( smap, smarker, lat, lon ) {
      smarker.setPosition( new google.maps.LatLng( lat, lon ) );
      smap.panTo( new google.maps.LatLng( lat, lon ) );
    };

    var inc = 0;
    function updatePerformers() {
      // should be doing this for all performers?
      navigator.geolocation.getCurrentPosition(
        function(p) {
          window.lat = p.coords.latitude;
          window.lon = p.coords.longitude;
          // console.log(lat,lon);
        },
        function(e) {
        }
      );
      console.log(window.lat,window.lon);
      moveMarker(map, marker, window.lat, window.lon);
    };

    function lookupPerformers() {
      navigator.geolocation.getCurrentPosition( function(p) {
        $.post( "/performers/lookup",
                { 'position': p.coords.latitude+','+p.coords.longitude }, function( data ) {
                console.log( 'receiving response!: ', data);
                } );
        // console.log(p.coords.latitude, p.coords.longitude)
      },
      function(e) {
      });
    };


    setInterval(function() {
      lookupPerformers();
      updatePerformers();
    }, 5000);





    </script>



  </head>
  <body style="background-color:gray">
    <!-- <div id="bg"> -->
    <div id="left">
      <h1>Map</h1>
      <h2>This will list all the nearby performers.</h2>

      <div style="background-color:white; border-style:solid; border-width:1px; border-color:black; text-align:left;">
        <form>
          <p>Search for Performers: <input type="text"/></p>
          <p>(Now only works by name)</p>


        </form>
      </div>

      <div id="firstentry" class="entry">
        <p>Name: Bruno Mars</p>
        <hr>
        <p>Styles:</p>
        <hr>
        <p>Distance:</p>
      </div>

      <div class="entry">
        <p>Name:</p>
        <hr>
        <p>Styles:</p>
        <hr>
        <p>Distance:</p>
      </div>

      <div class="entry">
        <p>Name:</p>
        <hr>
        <p>Styles:</p>
        <hr>
        <p>Distance:</p>
      </div>

      <div class="entry">
        <p>Name:</p>
        <hr>
        <p>Styles:</p>
        <hr>
        <p>Distance:</p>
      </div>

      <div class="entry">
        <p>Name:</p>
        <hr>
        <p>Styles:</p>
        <hr>
        <p>Distance:</p>
      </div>
    </div>
    <div id="map-canvas"/>

  </body>
</html>

app/app/views/performers/lookup.html.erb
<!DOCTYPE html>
<html>
  <head>

  </head>
  <body>
    <h1>List of Musicians</h1>
    <div id="bg"/>
    <div id="listholder">
      <input type="submit" value="Back" onclick="window.location='/';"/>
      <br/> </br>

      <% @performers.each do |p| %>
      <div class="listentry">
        <hr><p>email: <%= p.email %></p>
        <p>name: <%= p.name %></p>
      <!--       <td><%= link_to 'Destroy', performers_path(p), method: :delete %><hr></td>
            <br/> -->
        <p><%= link_to 'Profile', performers_edit_path(p) %></p>
      </div>



      <% end %>
    </div>
</body>
</html>

app/app/views/performers/new.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <div id="bg">
    <h1>Register Performer</h1>


    <%= form_for :performer, url: performers_path do |f| %>
    <% if @performer.errors.any? %>
        <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
                <% @performer.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :email %><br />
        <%= f.text_field :email %>
    </div>
    <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password %>
    </div>
    <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

<%= link_to 'Intro', root_path %>


  </body>
</html>

app/app/views/performers/search.html.erb
<!DOCTYPE html>
<html>
  <head>

  </head>
  <body>
    <h1>List of Musicians</h1>
    <div id="bg"/>
    <div id="listholder">
      <input type="submit" value="Back" onclick="window.location='/';"/>
      <br/> </br>

      <% @performers.each do |p| %>
      <div class="listentry">
        <hr><p>email: <%= p.email %></p>
        <p>name: <%= p.name %></p>
      <!--       <td><%= link_to 'Destroy', performers_path(p), method: :delete %><hr></td>
            <br/> -->
        <p><%= link_to 'Profile', performers_edit_path(p) %></p>
      </div>



      <% end %>
    </div>
</body>
</html>

app/app/views/performers/show.html.erb
<!DOCTYPE html>
<html>
  <head>

  </head>
  <body>
    <div id="bg">
    <h1><%= @performer.name %>'s Profile</h1>
    <h2>email: <%= @performer.email%> </h2>
    <br/><br/>


     <form style="display: block;" action="https://www.paypal.com/cgi-bin/webscr" method="post">
       <input type="hidden" name="cmd" value="_xclick">
       <input type="hidden" name="business" value="<%= @performer.email %>">
       <input type="hidden" name="item_name" value="BattleHack Bet">
       <input type="hidden" name="paymentaction" value="authorization">
       <input type="hidden" name="no_note" value="1">
       <input type="hidden" name="currency_code" value="USD">
       <select name="amount">
         <option value="1">1 $</option>
         <option value="3">3 $</option>
         <option value="5">5 $</option>
         <option value="10">10 $</option>
         <option value="20">20 $</option>
         <option value="30">30 $</option>
         <option value="50">50 $</option>
       </select><br/>
       <input type="submit" value="Send money" />
     </form>
  </body>
</html>

app/app/views/twilio/io.html.erb
<?xml version="1.0" encoding="UTF-8"?>
<Response><Sms>Thanks for the message. Configure your number's SMS URL to change this message.Reply HELP for help.Reply STOP to unsubscribe.Msg&amp;Data rates may apply.</Sms></Response>